backend:
  name: github
  branch: main
  repo: macro74523/Astro-theme
  site_domain: www.macro.wang
  base_url: https://www.macro.wang
  auth_endpoint: oauth

collections:
  - name: "note"
    label: "笔记"
    folder: "src/content/note"
    create: true
    slug: "{{year}}.{{month}}.{{day}}_{{slug}}"
    fields:
      - { label: "标题", name: "title", widget: "string", required: true }
      - {
          label: "简介",
          name: "description",
          widget: "string",
          default: "这是一篇有意思的文章",
          required: true,
        }
      - {
          label: "发布日期",
          name: "publishDate",
          widget: "datetime",
          date_format: "YYYY-MM-DD",
          time_format: "HH:mm",
          required: true,
        }
      - { label: "正文", name: "body", widget: "markdown" }

  - name: "post"
    label: "博文"
    folder: "src/content/post"
    create: true
    slug: "{{year}}.{{month}}.{{day}}_{{slug}}"
    fields:
      - { label: "标题", name: "title", widget: "string", required: true }
      - {
          label: "简介",
          name: "description",
          widget: "string",
          default: "这是一篇有意思的文章",
          required: true,
        }
      - {
          label: "发布日期",
          name: "publishDate",
          widget: "datetime",
          date_format: "YYYY-MM-DD",
          required: true,
        }
      - { label: "标签", name: "tags", widget: "list", required: true }
      - label: "封面图"
        name: "coverImage"
        widget: "object"
        required: false
        fields:
          - { label: "图片地址", name: "src", widget: "image", required: true }
          - { label: "图片描述", name: "alt", widget: "string", required: true }
      - {
          label: "ogImage",
          name: "ogImage",
          widget: "string",
          default: "/social-card.avif",
          required: false,
        }
      - { label: "正文", name: "body", widget: "markdown" }

media_folder: "public/assets/images"
public_folder: "/assets/images"